website/auth.py
from flask import Blueprint,render_template,request,flash,redirect,url_for,session,Response, send_file
from werkzeug.security import generate_password_hash,check_password_hash
from . import db
from sqlalchemy import func
from .models import User,ProfessionalDetails,Services,ServiceRequest,RejectedRequest
import os
import matplotlib.pyplot as plt
import io
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from datetime import datetime
#--------------------------------------------------------
def isValidPassword(password):
    u,l,s,d=False,False,False,False
    if len(password)<8:
        return False
    for i in range(len(password)):
        if password[i].isupper():
            u=True
        elif password[i].islower():
            l=True
        elif password[i].isdigit():
            d=True
        elif password[i] in "@$!%*?&":
            s=True
    return u and l and s and d

def isValidPincode(pincode):
    return len(pincode) == 6 and pincode.isdigit()

def isValidPhone(phone_number):
    return len(phone_number)==10 and phone_number.isdigit()

#-------------------------------------------------------

auth=Blueprint('auth',__name__)


@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        if email in ADMINS and password==ADMINS[email]:
            session['user_role']="admin"
            flash("Welcome Admin!","success")
            return redirect(url_for("auth.admin"))
        
        professional = ProfessionalDetails.query.filter_by(email=email).first()
        if professional:
            if professional.status == 'pending':
                flash("Your account is not approved by the admin yet.", "warning")
                return render_template("login.html")
            elif professional.status == 'rejected':
                flash("Your account has been rejected by the admin. Please contact support for assistance.", "danger")
                return render_template("login.html")
            if check_password_hash(professional.password, password):
                session["user_role"] = "professional"
                session["user_id"] = professional.id
                flash("Logged in successfully!", "success")
                return redirect(url_for("auth.services"))

        user=User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password,password):
            session["user_role"]="customer"
            session["user_id"]=user.id
            flash("Logged in successfully!","success")
            return redirect(url_for('auth.customer_dashboard'))
        flash("Invalid email or password", "danger")
        return render_template("login.html")
    
        
    return render_template("login.html")


#-------------------------------------------------------

@auth.route('/logout')
def logout():
    session.clear()
    flash("Logged out successfully!", "success")
    return redirect(url_for('auth.login'))

#-------------------------------------------------------

@auth.route("/customer-signup",methods=['GET','POST'])
def customer_signup():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        name = request.form.get('name')
        phone_number = request.form.get('pno')
        address = request.form.get('address')
        pincode = request.form.get('pincode')

        if not email or not password or not name or not address or not pincode:
            flash("All fields are required. Please fill in every field.", category="danger")
            return redirect(url_for('auth.customer_signup'))
        
        if not isValidPassword(password):
            flash("Password must be at least 8 characters long and contain uppercase, lowercase, number, and special character.", category="danger")
            return redirect(url_for('auth.customer_signup'))
        
        if not isValidPincode(pincode):
            flash("Pincode must be exactly 6 digits.", category="danger")
            return redirect(url_for('auth.customer_signup'))
        
        if not isValidPhone(phone_number):
            flash("Not a valid Phone number", category="danger")
            return redirect(url_for('auth.customer_signup'))
        
        exist=User.query.filter_by(email=email).first()
        if exist:
            flash("EmailID is already in use.", category="danger")
            return redirect(url_for('auth.customer_signup'))
        
        
        hashed_password=generate_password_hash(password)

        new_customer = User(
            email=email,
            password=hashed_password,
            name=name,
            address=address,
            pincode=pincode,
            phone_number=phone_number
        )
        db.session.add(new_customer)
        db.session.commit()
        flash("Registration successful, Welcome!", category="success")
        return redirect(url_for('auth.login'))

    return render_template('customer_signup.html')


#----------------------------------------------------

@auth.route("/prof-signup",methods=['GET','POST'])
def prof_signup():
    if request.method == 'POST':
        data=request.form
        print(data)
        email = request.form.get('email')
        password = request.form.get('password')
        name = request.form.get('name')
        phone_number = request.form.get('pno')
        service = request.form.get('service')
        experience = request.form.get('exp')
        address = request.form.get('address')
        pincode = request.form.get('pincode')

        if not email or not password or not name or not phone_number or not service or not experience or not address or not pincode:
            flash("All fields are required", category='error')
            return redirect(url_for('auth.prof_signup'))
        
        if service == "select":
            flash("Please select a service", category='error')
            return redirect(url_for('auth.prof_signup'))
        
        if not isValidPassword(password):
            flash("Password must be at least 8 characters long and contain uppercase, lowercase, number, and special character.", category='error')
            return redirect(url_for('auth.prof_signup'))

        if not isValidPincode(pincode):
            flash("Pincode must be exactly 6 digits.", category='error')
            return redirect(url_for('auth.prof_signup'))

        if not isValidPhone(phone_number):
            flash("Not a valid Phone number", category='error')
            return redirect(url_for('auth.prof_signup'))

        exist = ProfessionalDetails.query.filter_by(email=email).first()
        if exist:
            flash("EmailID is already in use.", category='error')
            return redirect(url_for('auth.login'))

        hashed_password = generate_password_hash(password)
        new_prof = ProfessionalDetails(
            email=email,
            password=hashed_password,  
            name=name,
            phone_number=phone_number,
            service=service,
            experience=experience,
            address=address,
            pincode=pincode
        )

        db.session.add(new_prof)
        db.session.commit()

        flash("Registration successful, Welcome!", category='success')
        return redirect(url_for('auth.login'))


    return render_template('prof-signup.html')

#-------------------------Professional routes------------------------------------

@auth.route('/services', methods=['POST', 'GET'])
def services():
    if not session.get('user_role') or session['user_role'] != 'professional':
        return redirect(url_for('auth.login'))

    professional_id = session.get('user_id')
    professional = ProfessionalDetails.query.get(professional_id)

    subquery = db.session.query(RejectedRequest.service_request_id).filter(
        RejectedRequest.professional_id == professional_id
    ).subquery()

    service_requests = ServiceRequest.query.filter(
        ServiceRequest.professional_id.is_(None),
        ServiceRequest.status == "Requested",
        ~ServiceRequest.id.in_(subquery),
        ServiceRequest.service.has(domain=professional.service)
    ).all()

    closed_requests = ServiceRequest.query.filter_by(professional_id=professional_id, status='closed').all()
    return render_template('professional_dashboard.html', service_requests=service_requests, closed_requests=closed_requests)


@auth.route('/accept_request/<int:request_id>', methods=['GET','POST'])
def accept_request(request_id):
    if 'user_role' not in session or session['user_role'] != "professional":
        flash("Please log in as a professional to accept requests", "danger")
        return redirect(url_for("auth.login"))

    professional_id = session['user_id']
    request = ServiceRequest.query.get_or_404(request_id)
    if request.status == "Requested" and request.professional_id is None:
        request.status = "accepted"
        request.professional_id = professional_id
        db.session.commit()

        flash(f"Service request {request.id} accepted", "success")
    else:
        flash(f"Service request {request.id} cannot be accepted", "danger")

    return redirect(url_for("auth.services"))
   
@auth.route('/reject_request/<int:request_id>', methods=['GET','POST'])
def reject_request(request_id):
    professional_id = session.get('user_id')
    service_request = ServiceRequest.query.get(request_id)

    if service_request:
        rejection = RejectedRequest(service_request_id=request_id, professional_id=professional_id)
        db.session.add(rejection)
        db.session.commit()
        flash("Service request rejected successfully.", "info")
    else:
        flash("Service request not found.", "danger")

    return redirect(url_for('auth.services'))

@auth.route('/close_request/<int:request_id>', methods=['POST'])
def close_request(request_id):

website/templates/admin_dashboard.html
{%extends 'base.html'%} 
{% include 'flash_msg.html' with context %} 
{% block body %}
<div class="container mt-4">
  <h4>Services</h4>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Service Domain</th>
        <th>Service Name</th>
        <th>Base Price</th>
        <th>Action</th>
        <tbody>
          {%for service in services%}
          <tr>
            <td>
              <a href="#" data-bs-toggle="modal" data-bs-target="#serviceModal{{service.id}}">
                {{service.id}}
              </a>
            </td>
            <td>{{service.domain}}</td>
            <td>{{service.name}}</td>
            <td>{{service.price}}</td>
            <td>
              <button
                class="btn btn-primary"
                data-bs-toggle="modal"
                data-bs-target="#editServiceModal{{service.id}}"
              >
                Edit
              </button>
              <form action="{{ url_for('auth.delete_service', service_id=service.id) }}" method="POST" style="display:inline;">
                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this service?')">
                  Delete
                </button>
              </form>
            </td>
          </tr>
          <div class="modal fade" id="editServiceModal{{service.id}}" tabindex="-1" aria-labelledby="editServiceModalLabel{{service.id}}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="editServiceModalLabel{{service.id}}">Edit Service</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form action="{{ url_for('auth.edit_service', service_id=service.id) }}" method="POST">
                    <label for="domain" class="form-label mt-3">Service Domain</label>
                    <input type="text" name="domain" id="domain" value="{{ service.domain }}" class="form-control">
    
                    <label for="name" class="form-label mt-3">Service Name</label>
                    <input type="text" name="name" id="name" value="{{ service.name }}" class="form-control">
    
                    <label for="description" class="form-label mt-3">Description</label>
                    <input type="text" name="description" id="description" value="{{ service.description }}" class="form-control">
    
                    <label for="price" class="form-label mt-3">Price</label>
                    <input type="number" name="price" id="price" value="{{ service.price }}" class="form-control">
    
                    <div class="text-center">
                      <button class="btn btn-primary mt-4" type="submit">Update</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </tbody>
      </tr>
    </thead>
  </table>
  <button
    type="button"
    class="btn btn-primary"
    data-bs-toggle="modal"
    data-bs-target="#addservice"
  >
    Add Service
  </button>

  <!--Table for Professional Status-->

  <h4 class="mt-4">Professionals</h4>
  <table class="table">
    <thead>
        <tr><th>ID</th><th>Name</th><th>Experience</th><th>Service</th><th>Action</th></tr>
    </thead>
    <tbody>
        {% for professional in professionals %}
        <tr>
            <td>
              <a href="#" data-bs-toggle="modal" data-bs-target="#professionalModal{{professional.id}}">
                {{professional.id}}
              </a>
            </td>
            <td>{{professional.name}}</td>
            <td>{{professional.experience}} yrs</td>
            <td>{{professional.service}}</td>
            <td>
              <td>
                {% if professional.status == 'pending' %}
                  <a href="{{url_for('auth.approve_professional', professional_id=professional.id)}}" class="btn btn-success btn-sm">Approve</a>
                  <a href="{{url_for('auth.reject_professional', professional_id=professional.id)}}" class="btn btn-danger btn-sm">Reject</a>
                {% elif professional.status == 'approved' %}
                  <span class="text-success text-center">Approved</span>
                {% elif professional.status == 'rejected' %}
                  <span class="text-danger">Rejected</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

  <!--Model for Service details-->
  
  {% for service in services %}
  <div
  class="modal fade"
  id="serviceModal{{service.id}}"
  tabindex="-1"
  aria-labelledby="serviceModalLabel{{service.id}}"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="serviceModalLabel{{service.id}}">Service Details</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <p><strong>ID:</strong> {{ service.id }}</p>
        <p><strong>Domain:</strong> {{ service.domain }}</p>
        <p><strong>Name:</strong> {{ service.name }}</p>
        <p><strong>Description:</strong> {{ service.description }}</p>
        <p><strong>Base Price:</strong> Rs.{{ service.price }}</p>
      </div>
    </div>
  </div>
</div>
  {% endfor %}

  <!--Model to add service-->

  <div
    class="modal fade"
    id="addservice"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div
      class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg"
    >
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Add a Service</h1>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <div class="container col-12 col-md-6 center bg-white">
            <form action="/admin" method="POST">
              <label for="domain" class="form-label mt-1">Service Domain</label>
              <input
                type="text"
                name="domain"
                id="domain"
                placeholder=""
                class="form-control"
              />
              <label for="name" class="form-label mt-3">Service Name</label>
              <input
                type="text"
                name="name"
                id="name"
                placeholder=""
                class="form-control"
              />
              <label for="description" class="form-label mt-3"
                >Description</label
              >
              <input
                type="text"
                name="description"
                id="description"
                placeholder=""
                class="form-control"
              />
              <label for="price" class="form-label mt-3">Price</label>
              <input
                type="number"
                name="price"
                id="price"
                placeholder=""
                class="form-control"
              />
              <div class="text-center">
                <button class="btn btn-primary mt-4" type="submit">Add</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!--Modal for Professinal details-->
  {%for professional in professionals%}
  <div class="modal fade" id="professionalModal{{professional.id}}" tabindex="-1" aria-labelledby="professionalModalLabel{{professional.id}}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="professionalModalLabel{{professional.id}}">Professional Details</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p><strong>ID:</strong> {{ professional.id }}</p>
          <p><strong>Name:</strong> {{ professional.name }}</p>
          <p><strong>Experience:</strong> {{ professional.experience }} years</p>
          <p><strong>Service Domain:</strong> {{ professional.service }}</p>
          <p><strong>Status:</strong> {{ professional.status }}</p>
        </div>
      </div>
    </div>
  </div>
  {%endfor%}
</div>
{%endblock%}

website/templates/admin_summary.html
{% extends 'base.html' %}
{% include 'flash_msg.html' with context %}
{% block body %}
<div class="container mt-5">
    <h2>Admin Summary</h2>
    <div class="row">
    <div class="mt-4 col-md-6">
        <h3>Overall Customer Ratings</h3>
        <img src="{{url_for('auth.overall_customer_ratings')}}" alt="Customer Ratings Graph" class="img-fluid">
    </div>

    <div class="mt-4 col-md-6">
        <h3>Service Requests Summary</h3>
        <img src="{{url_for('auth.service_requests_summary')}}" alt="Service Requests Summary" class="img-fluid">
    </div>
    </div>
</div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{%block title%}{%endblock%}</title>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

  </head>
  <body class="bg-light">
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary " >
  <div class="container-fluid">
    <a class="navbar-brand" href="/">HomeEase</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {%if session.get('user_role') == 'admin'%}
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.admin')}}">Home</a></li>
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.search_admin_requests')}}">Search</a></li>
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.admin_summary')}}">Summary</a></li>
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.logout')}}">Logout</a></li>
        </ul>
        {%elif session.get('user_role') == 'customer'%}
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.customer_dashboard')}}">Home</a></li>
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.search_services')}}">Search</a></li>
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.customer_summary')}}">Summary</a></li>
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.logout')}}">Logout</a></li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.customer_profile')}}">
              <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
              </svg>
            </a>
          </li>
        </ul>
        {%elif session.get('user_role') == 'professional'%}
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.services')}}">Home</a></li>
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.search_professional_requests')}}">Search</a></li>
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.professional_summary')}}">Summary</a></li>
            <li class="nav-item"><a class="nav-link active" href="{{url_for('auth.logout')}}">Logout</a></li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0" >
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.professional_profile')}}">
              <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
              </svg>
            </a>
          </li>
        </ul>
        {%else%}
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/customer-signup">sign up</a>
        </li>
        </ul>
        {%endif%}
  
    </div>
  </div>
    </nav>
    <div class="container ">{%block body%}{%endblock%}</div>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>


</html>

website/templates/customer_dashboard.html
{% extends 'base.html' %}
{% include 'flash_msg.html' with context %}
{% block body %}
<div class="container mt-4">
    <p>Hello,{{current_customer.name}}</p>
    <h4>Looking for?</h4>
    <div class="d-flex overflow-auto" >
        {%for category in categories%}
        <div class="card me-2 mb-3" style="width: 18rem;">
            <div class="card-body">
                <h4>{{category}}</h4>
                <a href="{{url_for('auth.packages',category=category)}}" class="btn btn-primary">Explore Now!</a>
            </div>
        </div>
        {%endfor%}      
    </div>
    

    <h4 class="mt-4">Service History</h4>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Service Name</th>
                <th>Professional Name</th>
                <th>Phone Number</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for request in service_requests %}
            <tr>
                <td>{{request.id}}</td>
                <td>{{request.service.name}}</td>
                {%if request.professional.name==NULL%}
                    <td><p>Not assigned yet.</p></td>
                    <td><p>-</p></td>
                {%else%}
                <td>{{request.professional.name}}</td>
                <td>{{request.professional.phone_number[:2]}}XXXXXX</td>
                {%endif%}
                {%if request.status=='accepted'%}
                <td>
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#closeServiceModal{{ request.id }}">
                        Close it?
                    </button>
                    <div class="modal fade" id="closeServiceModal{{ request.id }}" tabindex="-1" aria-labelledby="closeServiceLabel{{ request.id }}" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-lg">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="closeServiceLabel{{ request.id }}">Service Remarks</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <form action="{{url_for('auth.close_request', request_id=request.id)}}" method="POST">
                                    <div class="modal-body">
                                        <div class="row mb-3">
                                            <div class="col-4"><strong>Service Name:</strong> {{ request.service.name }}</div>
                                            <div class="col-4"><strong>Description:</strong> {{ request.service.description }}</div>
                                            <div class="col-4"><strong>Date Created:</strong> {{ request.date_created.strftime('%Y-%m-%d') }}</div>
                                        </div>
        
                                        <div class="row mb-3">
                                            <div class="col-4"><strong>Professional ID:</strong> {{ request.professional.id }}</div>
                                            <div class="col-4"><strong>Professional Name:</strong> {{ request.professional.name }}</div>
                                            <div class="col-4"><strong>Contact No.:</strong> {{ request.professional.phone_number }}</div>
                                        </div>
        
                                        <div class="mb-3">
                                            <label for="rating{{request.id}}" class="form-label">Service Rating (out of 5):</label>
                                            <input type="number" name="rating" id="rating{{request.id}}" class="form-control" min="1" max="5" required>
                                        </div>
        
                                        <div class="mb-3">
                                            <label for="remarks{{request.id}}" class="form-label">Remarks (if any):</label>
                                            <textarea name="remarks" id="remarks{{request.id}}" class="form-control" rows="3"></textarea>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-primary">Submit and Close</button>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </td>
                {%else%}
                    <td>{{request.status}}</td>
                {%endif%}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

website/templates/customer_summary.html
{% extends "base.html" %}
{% include 'flash_msg.html' with context %}
{% block body %}
<div class="container mt-5">
    <h2>Customer Service Requests Summary</h2>
    <img src="{{url_for('auth.customer_service_requests_graph')}}" alt="Customer Service Requests Graph" class="img-fluid">
</div>

{%endblock%}

website/templates/professional_dashboard.html
{%extends 'base.html'%}
{% include 'flash_msg.html' with context %}
{% block body %}
<div class="container mt-5">
    <h2>Services available</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Customer Name</th>
                <th>Service</th>
                <th>Contact</th>
                <th>Location</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for request in service_requests %}
            <tr>
                <td>{{request.id}}</td>
                <td>{{request.customer.name}}</td>
                <td>{{request.service.name}}</td>
                <td>{{request.customer.phone_number}}</td>
                <td>{{request.customer.address}}</td>
                <td>
                    <a href="{{url_for('auth.accept_request', request_id=request.id)}}" class="btn btn-success">Accept</a>
                    <a href="{{url_for('auth.reject_request', request_id=request.id)}}" class="btn btn-danger">Reject</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h2 class="mt-5">Closed Services</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Customer Name</th>
                <th>Contact Phone</th>
                <th>Location</th>
                <th>Date Closed</th>
                <th>Rating</th>
            </tr>
        </thead>
        <tbody>
            {% for closed in closed_requests %}
            <tr>
                <td>{{closed.id}}</td>
                <td>{{closed.customer.name}}</td>
                <td>{{closed.customer.phone_number}}</td>
                <td>{{closed.customer.address}}</td>
                <td>{{closed.date_created.strftime('%Y-%m-%d')}}</td>
                <td>
                    {% if closed.rating %}
                        {{closed.rating}}/5
                    {% else %}
                        Not Rated
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{%endblock%}